// lib/localization/app_localizations.dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class AppLocalizations extends Translations {
  static const Locale turkish = Locale('tr', 'TR');
  static const Locale english = Locale('en', 'US');
  static final List<Locale> supportedLocales = [turkish, english];

  @override
  Map<String, Map<String, String>> get keys => {
        'tr_TR': {
          // Uygulama
          'app_title': 'CineFlow',
          'movie_explorer': 'Film Keşif',
          'playback': 'Oynatma',
          // Navigasyon
          'home': 'Ana Sayfa',
          'movies': 'Filmler',
          'tv_shows': 'TV Dizileri',
          'favorites': 'Favoriler',
          'actors': 'Oyuncular',
          'profile': 'Profil',
          'settings': 'Ayarlar',
          // Arama
          'search_movies': 'Film ara...',
          'search_tv_shows': 'TV Dizi ara...',
          'no_results': 'Sonuç bulunamadı.',
          'search_history': 'Arama Geçmişi',
          'search_actors': 'Oyuncu ara (ör. Şahin)...',
          'assistant_input_hint': 'Örn: Üzgünken izleyebileceğim filmler öner...',
          // Filmler
          'popular_movies': 'Popüler Filmler',
          'top_rated_movies': 'En İyi Filmler',
          'upcoming_movies': 'Yakında Çıkacak',
          'now_playing': 'Şimdi Oynatılıyor',
          // TV Dizileri
          'popular_tv_shows': 'Popüler TV Dizileri',
          'top_rated_tv_shows': 'En İyi TV Dizileri',
          'on_the_air': 'Şu Anda Yayınlananlar',
          'airing_today': 'Bugün Yayınlananlar',
          // Filtre
          'apply_filters': 'Filtreleri Uygula',
          'reset_filters': 'Filtreleri Sıfırla',
          'sort_by': 'Sırala',
          'sort_by_popularity': 'Popülerliğe Göre',
          'sort_by_newest': 'En Yeni Filmler',
          'sort_by_oldest': 'En Eski Filmler',
          'sort_by_highest_rated': 'En Yüksek Puanlılar',
          'sort_by_lowest_rated': 'En Düşük Puanlılar',
          'release_year': 'Yayın Yılı',
          'rating': 'Puan',
          // Profil
          'my_favorites': 'Favorilerim',
          'watchlist': 'İzleme Listem',
          'watch_history': 'İzleme Geçmişim',
          'about': 'Hakkında',
          'sign_out': 'Çıkış Yap',
          'no_favorites_found': 'Favori film bulunamadı.',
          'no_favorites_found_desc': 'Favori filmleri buraya ekleyin.',
          'no_watchlist_found': 'İzleme listesi boş.',
          'no_watchlist_found_desc': 'İzlemek istediğin filmleri buraya ekle.',
          'no_history_found': 'İzleme geçmişi boş.',
          'no_history_found_desc': 'İzlediğin filmler burada görünecek.',
          'explore_movies': 'Film Keşfet',
          'total_favorites': 'Toplam Favori',
          'total_watchlist': 'Toplam İzleme Listesi',
          'total_history': 'Toplam Geçmiş',
          // Ayarlar
          'theme': 'Tema',
          'light_theme': 'Açık Tema',
          'dark_theme': 'Koyu Tema',
          'system_default': 'Sistem Varsayılanı',
          'language': 'Dil',
          'notifications': 'Bildirimler',
          'general': 'Genel',
          'video_quality': 'Video Kalitesi',
          'auto_play_trailer': 'Fragmanları Otomatik Oynat',
          'save_settings': 'Ayarları Kaydet',
          'privacy_policy': 'Gizlilik Politikası',
          'terms_of_use': 'Kullanım Koşulları',
          // Detay
          'trailer': 'Fragman',
          'cast': 'Oyuncular',
          'details': 'Detaylar',
          'director': 'Yönetmen',
          'writer': 'Yazar',
          'status': 'Durum',
          'genres': 'Türler',
          'runtime': 'Süre',
          'overview': 'Genel Bakış',
          'similar_movies': 'Benzer Filmler',
          'recommendations': 'Öneriler',
          'not_available': 'Mevcut değil',
          // Film Durumu
          'released': 'Yayınlandı',
          'rumored': 'Söylenti',
          'planned': 'Planlandı',
          'in_production': 'Yapım Aşamasında',
          'post_production': 'Post Prodüksiyon',
          'cancelled': 'İptal Edildi',
          // Ağ
          'network': 'Ağ',
          'original_network': 'Orijinal Ağ',
          'first_air_date': 'İlk Yayın Tarihi',
          'last_air_date': 'Son Yayın Tarihi',
          'number_of_seasons': 'Sezon Sayısı',
          'number_of_episodes': 'Bölüm Sayısı',
          // Bütçe ve Hasılat
          'budget': 'Bütçe',
          'revenue': 'Hasılat',
          'box_office': 'Gişe',
          'production_companies': 'Yapım Şirketleri',
          'production_countries': 'Yapım Ülkeleri',
          // Dil ve Ülke
          'original_language': 'Orijinal Dil',
          'spoken_languages': 'Konuşulan Diller',
          // ignore: equal_keys_in_map
          'production_countries': 'Yapım Ülkeleri',
          // Bildirimler
          'new_release': 'Yeni Yayın',
          'favorite_actor_movie': 'Favori Aktör Filmi',
          'reminder': 'Hatırlatıcı',
          'news': 'Haberler',
          // Hatalar
          'network_error': 'Ağ Hatası',
          'server_error': 'Sunucu Hatası',
          'unknown_error': 'Bilinmeyen Hata',
          'no_internet': 'İnternet Bağlantısı Yok',
          'try_again_later': 'Lütfen daha sonra tekrar deneyin.',
          // Başarı
          'added_to_favorites': 'Favorilere eklendi',
          'removed_from_favorites': 'Favorilerden çıkarıldı',
          'settings_saved': 'Ayarlar kaydedildi',
          'profile_updated': 'Profil güncellendi',
          'filters_reset': 'Filtreler sıfırlandı',
          'filters_reset_desc': 'Tüm filtreler başlangıç değerlerine döndürüldü.',
        },
        'en_US': {
          // App
          'app_title': 'CineFlow',
          'movie_explorer': 'Movie Explorer',
          'playback': 'Playback',
          // Navigation
          'home': 'Home',
          'movies': 'Movies',
          'tv_shows': 'TV Shows',
          'favorites': 'Favorites',
          'actors': 'Actors',
          'profile': 'Profile',
          'settings': 'Settings',
          // Search
          'search_movies': 'Search movies...',
          'search_tv_shows': 'Search TV shows...',
          'no_results': 'No results found.',
          'search_history': 'Search History',
          'search_actors': 'Search actors (e.g. Şahin)...',
          'assistant_input_hint': 'E.g. Suggest movies I can watch when I feel sad...',
          // Movies
          'popular_movies': 'Popular Movies',
          'top_rated_movies': 'Top Rated Movies',
          'upcoming_movies': 'Upcoming',
          'now_playing': 'Now Playing',
          // TV Shows
          'popular_tv_shows': 'Popular TV Shows',
          'top_rated_tv_shows': 'Top Rated TV Shows',
          'on_the_air': 'On The Air',
          'airing_today': 'Airing Today',
          // Filter
          'apply_filters': 'Apply Filters',
          'reset_filters': 'Reset Filters',
          'sort_by': 'Sort By',
          'sort_by_popularity': 'By Popularity',
          'sort_by_newest': 'Newest',
          'sort_by_oldest': 'Oldest',
          'sort_by_highest_rated': 'Highest Rated',
          'sort_by_lowest_rated': 'Lowest Rated',
          'release_year': 'Release Year',
          'rating': 'Rating',
          // Profil
          'my_favorites': 'My Favorites',
          'watchlist': 'My Watchlist',
          'watch_history': 'Watch History',
          'about': 'About',
          'sign_out': 'Sign Out',
          'no_favorites_found': 'No favorite movies found.',
          'no_favorites_found_desc': 'Add favorite movies here.',
          'no_watchlist_found': 'Watchlist is empty.',
          'no_watchlist_found_desc': 'Add movies you want to watch here.',
          'no_history_found': 'Watch history is empty.',
          'no_history_found_desc': 'Movies you have watched will appear here.',
          'explore_movies': 'Explore Movies',
          'total_favorites': 'Total Favorites',
          'total_watchlist': 'Total Watchlist',
          'total_history': 'Total History',
          // Ayarlar
          'theme': 'Theme',
          'light_theme': 'Light Theme',
          'dark_theme': 'Dark Theme',
          'system_default': 'System Default',
          'language': 'Language',
          'notifications': 'Notifications',
          'general': 'General',
          'video_quality': 'Video Quality',
          'auto_play_trailer': 'Auto-Play Trailer',
          'save_settings': 'Save Settings',
          'privacy_policy': 'Privacy Policy',
          'terms_of_use': 'Terms of Use',
          // Detay
          'trailer': 'Trailer',
          'cast': 'Cast',
          'details': 'Details',
          'director': 'Director',
          'writer': 'Writer',
          'status': 'Status',
          'genres': 'Genres',
          'runtime': 'Runtime',
          'overview': 'Overview',
          'similar_movies': 'Similar Movies',
          'recommendations': 'Recommendations',
          'not_available': 'Not available',
          // Film Durumu
          'released': 'Released',
          'rumored': 'Rumored',
          'planned': 'Planned',
          'in_production': 'In Production',
          'post_production': 'Post Production',
          'cancelled': 'Cancelled',
          // Ağ
          'network': 'Network',
          'original_network': 'Original Network',
          'first_air_date': 'First Air Date',
          'last_air_date': 'Last Air Date',
          'number_of_seasons': 'Number of Seasons',
          'number_of_episodes': 'Number of Episodes',
          // Bütçe ve Hasılat
          'budget': 'Budget',
          'revenue': 'Revenue',
          'box_office': 'Box Office',
          'production_companies': 'Production Companies',
          'production_countries': 'Production Countries',
          // Dil ve Ülke
          'original_language': 'Original Language',
          'spoken_languages': 'Spoken Languages',
          // ignore: equal_keys_in_map
          'production_countries': 'Production Countries',
          // Bildirimler
          'new_release': 'New Release',
          'favorite_actor_movie': 'Favorite Actor Movie',
          'reminder': 'Reminder',
          'news': 'News',
          // Hatalar
          'network_error': 'Network Error',
          'server_error': 'Server Error',
          'unknown_error': 'Unknown Error',
          'no_internet': 'No Internet Connection',
          'try_again_later': 'Try again later.',
          // Başarı
          'added_to_favorites': 'Added to favorites',
          'removed_from_favorites': 'Removed from favorites',
          'settings_saved': 'Settings saved',
          'profile_updated': 'Profile updated',
          'filters_reset': 'Filters reset',
          'filters_reset_desc': 'All filters have been reset to default values.',
        },
      };
}
